site_name: xRSA
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.follow
plugins:
- search
- mkdocstrings
- autorefs
- gen-files:
    scripts:
    - docs/gen_ref_pages.py
- literate-nav:
    tab_length: 4
    nav_file: SUMMARY.md
- section-index
- mkdocstrings:
    handlers:
      python:
        paths: [src]
nav:
  - Home: docs/index.md
  - Code Reference: reference/

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.magiclink
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      check_paths: true
  - callouts
  - admonition
  - md_in_html
  - toc:
      permalink: "#"
