abbrev_ord_by_fp = {
    'ecfp': ['+pul',
             'menth',
             'long',
             'sab',
             '-bCar',
             '-aPine',
             'euc',
             '2-mib',
             'geos',
             'guai',
             'mchav',
             'PEA',
             'PAA',
             'bbenz',
             'B-myr',
             'ger',
             '1-prop',
             '1p3one',
             '1o3one',
             'EtOct',
             '2-mba',
             'Z4-7al']
    }
